- readme.md
- src/main/kotlin/org/jetbrains/kotlin/jupyter/ikotlin.kt
It allows basic syntax highlighting for a notebook source code.
> add language_info to kernel_info_reply

- build.gradle
Installation of the kernel fails if the kernel install directory does not exist. This fix ensures that the missing directories are created so the installation succeeds in this scenario.
> Create installation directory if it does not exist

- readme.md
And as always been.
The repository description could be fixed as well, but can't be done via PRs
--- 
Happy to this this. Feel free to make and announce on the Jupyter/IPython mailing list.
Thanks !
> IPython is upper case I

- src/main/kotlin/org/jetbrains/kotlin/jupyter/protocol.kt
Currently trying to use nbconvert to script on Notebooks with a Kotlin kernel fails with the error below. This pull request fixes this.
```
$ jupyter nbconvert ktnotebook.ipynb --to script
[NbConvertApp] Converting notebook day01kt.ipynb to script
Traceback (most recent call last):
File "/home/mpcjanssen/.local/bin/jupyter-nbconvert", line 11, in <module>
sys.exit(main())
File "/home/mpcjanssen/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 268, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/home/mpcjanssen/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
app.start()
File "/home/mpcjanssen/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 340, in start …
```
> Fix file extension in language_info

- README.md
- build.gradle
- doc/magics.md
- src/main/kotlin/org/jetbrains/kotlin/jupyter/config.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/connection.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/magics.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/protocol.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/repl.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/capturingStreamTests.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/executeTests.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/kernelServerTestsBase.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/replTests.kt
Closes #32 
Send output to client before the whole cell is calculated. May be triggered by:
1) Exceeding buffer limit
2) Newline symbol in output
3) Some time after no flushing was performed
New and old functionality was covered with tests.
New config parameters were added
> Improved output capturing and added tests

- build.gradle.kts
- buildSrc/src/main/kotlin/install.kt
- buildSrc/src/main/kotlin/util.kt
- buildSrc/src/main/kotlin/versionDetection.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/config.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/util.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/configTests.kt
Branch and format version were actually defined in several different places, and it might be easy to forget to modify it in both places. We've actually forgot to do so, and that led to #66 
This PR places build branch and format version to runtime properties `.ini`, so now we should only change formatVersion in one place, and shouldn't change branch at all. If smb wants to build jupyter locally and use libraries branch different from what s/he's on, s/he should set `build.branch` gradle property locally.
> Move branch and formatVersion to runtime properties

- gradle.properties
- libraries/lets-plot.json
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/configTests.kt
- Add support for GGBunch
- Add support for method `show()` in plot and GGBunch
> Upgrade lets-plot version to 1.4.2

- libraries/lets-plot.json
- facet_grid() 
- coord_fixed()
- labs(), xlab(), ylab()
- lims(), xlim(), ylim()
- as_discrete()
- Geoms:
- geom_jitter()
- geom_bin2d(), stat_bin2d()
- geom_contour(), stat_contour()
- geom_contourf()
- geom_density2d(), stat_density2d()
- geom_density2df()
- geom_smooth(), stat_smooth()
- stat_bin()
- Manual scales:
- scale_fill_manual(), scale_color_manual()
- scale_size_manual()
- scale_shape_manual()
- scale_linetype_manual()
- scale_alpha_manual()
- Identity scales:
- scale_color_identity(), scale_fill_identity()
- scale_shape_identity()
- scale_linetype_identity()
- scale_alpha_identity()
- scale_size_identity()
- Positional scales:
- scale_x_continuous(), scale_y_continuous()
- scale_x_discrete(), scale_y_discrete()
- Brewer color scales:
- scale_color_brewer(), …
> Upgrade Lets-Plot Kotlin API to v. 0.0.22-SNAPSHOT

- src/main/kotlin/org/jetbrains/kotlin/jupyter/config.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/ikotlin.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/repl.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/embeddingTest.kt
Currently the Kotlin kernel supports something similar to [IPython.start_kernel](https://ipython.readthedocs.io/en/stable/api/generated/IPython.html#IPython.start_kernel). This PR aims to support something that covers the use cases of [IPython.embed_kernel](https://ipython.readthedocs.io/en/stable/api/generated/IPython.html#IPython.embed_kernel).
An application can now call `org.jetbrains.kotlin.jupyter.iKotlin.kernelServer` directly and pass a desired `KernelConfig` and the runtime properties where the `embedded` property is set to `true` and return the `KernelConfig` as a standard JSON to user in an application specific way.
The user can then run `jupyter console --existing=path/to/kernelconfig.json` to attach a Kotlin REPL to the kernel and run arbitrary Kotlin code inside the …
> Allow REPL/Kernel to be embedded and share classes/variables with its caller

- .run/Install for Java 8.run.xml
- gradle.properties
- libraries/fuel.json
- libraries/kaliningraph.json
- libraries/lets-plot.json
- settings.gradle.kts
- src/main/kotlin/org/jetbrains/kotlin/jupyter/config.kt
- src/main/kotlin/org/jetbrains/kotlin/jupyter/resolver.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/replTests.kt
- src/test/kotlin/org/jetbrains/kotlin/jupyter/test/typeProviderTests.kt
> Change added repositories order

- src/main/kotlin/org/jetbrains/kotlinx/jupyter/message_types.kt
> Fill HistoryRequest fields

- src/main/kotlin/org/jetbrains/kotlinx/jupyter/protocol.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/embeddingTest.kt
This tries is intended as a  fix for https://github.com/GhidraJupyter/ghidra-jupyter-kotlin/issues/2
Using ` exitProcess(0)` will terminate the entire process, but if the kernel is used as a library and embedded in another application, i.e. process this will be terminated too. Instead the code that handles the ShutdownRequest now has a somewhat inelegant check if the kernel is embedded and will instead just throw an `InterruptedException` which is caught in the controlThread loop and leads to the `controlThread` interrupting the `mainThread` so they both terminate and the entire kernel terminates.
Because I don't know why `exitProcess(0)` was used in the first place this will only happen if the kernel is embedded for now, but if this also works for the regular usage this could be …
> Don't kill process when embedded

- src/main/kotlin/org/jetbrains/kotlinx/jupyter/ikotlin.kt
EmptyResolutionInfoProvider is created by an [object declaration](https://kotlinlang.org/docs/object-declarations.html#object-declarations) which fails to import in pure java code. The `embedKernel` method is intended to be called inside pure Java code that simply has the compiled kotlin kernel jars available as a dependency, but the former signature after the refactor in https://github.com/Kotlin/kotlin-jupyter/commit/782f0882ed5f9e89ad378b4a986591397027721d#diff-3c1c4b1ddbb3338fe28601f266bb3c492ac38a395dafb1c3ad4b60a8ffeedc62R85 makes this impossible. This commit makes the `resolutionInfoProvider` nullable again, which also means that existing code using the method and passing null, still works with the the signature using `ResolutionInfoProvider`
edit 1: I can't see the build details, …
> Make embedKernel arguments nullable

- docs/README.md
- libraries/plotly-server.json
- libraries/plotly.json
* New package name
* version 0.4.0
* mavenCentral
> Update plotly.kt descriptors

- gradle.properties
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/GraphNode.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/Label.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/NodeWrapper.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/labels/FilteringPropObjectLabel.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/labels/KClassLabel.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/labels/PropObjectLabel.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/labels/RecordTableLabel.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/graphs/labels/TextLabel.kt
- jupyter-lib/lib-ext/build.gradle.kts
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/structure/DirectedEdge.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/structure/Graph.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/structure/GraphImpl.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/structure/MultiGraph.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/structure/MultiGraphImpl.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/structure/UndirectedEdge.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/structure/util.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/visualization/graphViz.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/wrappers/ClassLoaderNode.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/graph/wrappers/KClassNode.kt
- jupyter-lib/lib-ext/src/main/kotlin/org/jetbrains/kotlinx/jupyter/ext/integration/Integration.kt
- jupyter-lib/lib-ext/src/test/kotlin/org/jetbrains/kotlinx/jupyter/ext/RenderingTests.kt
- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/config/defaultImports.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/ResolverTests.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/CustomLibraryResolverTests.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/IntegrationApiTests.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/ReplWithResolverTests.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/testUtil.kt
API for different hierarchies visualization.
Visualize class types hierarchy and classloaders hierarchy:
It is easy to define own wrappers for KMath expressions, KotlinDL network layers, Dataframe hierarchical keys, and so on.
Examples:
```kotlin
class HKClass(node: KClass<*>) : NodeWrapper<KClass<*>>(node) {
override val ingoingEdges by lazy {
node.superclasses.map { HKClass(it) }
}
}
class HClassLoader(node: ClassLoader) : NodeWrapper<ClassLoader>(node) {
override val ingoingEdges by lazy {
node.parent?.let { listOf(HClassLoader(it)) } ?: emptyList()
}
override val label: String get() {
return when (node) {
is URLClassLoader -> node.urLs.joinToString("\\n", "URL ClassLoader:\\n") {
it.toString()
}
else -> node.toString()
}
}
}
```
> Add hierarchies visualization API to lib-ext

- build.gradle.kts
- docs/README.md
- gradle.properties
- jupyter-lib/lib/src/main/kotlin/jupyter/kotlin/annotations.kt
- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/dependencies/RemoteResolverWrapper.kt
- libraries/serialization.json
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/dependencies/JupyterScriptDependenciesResolverImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl.kt
- src/main/resources/logback.xml
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/ResolverTests.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/ReplTests.kt
PRs that need to be merged in Kotlin for this one:
Fixes #121, because mavenLocal is used as cache.
Also fixes #117.
Also adds repository authorization, cc @belovrv 
```kotlin
@file:Repository("https://url", "<username>", "<password>")
```
> Switch to Maven dependencies resolver

- libraries/lets-plot-gt.json
- libraries/lets-plot.json
Artifact "lets-plot-kotlin-api-kernel" was renamed to "lets-plot-kotlin-kernel"
CDN changed to JSDELIVR (was CDNJS)
Other: CHANGELOG
> Upgrade to Lets-Plot v2.0.4, Lets-Plot Kotlin API v3.0.1

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- jupyter-lib/kotlin-jupyter-api-gradle-plugin/build.gradle.kts
- kotlin-jupyter-plugin/build.gradle.kts
- kotlin-jupyter-plugin/settings.gradle.kts
- kotlin-jupyter-plugin/src/main/kotlin/org/jetbrains/kotlinx/jupyter/build/util.kt
- kotlin-jupyter-plugin/src/main/kotlin/org/jetbrains/kotlinx/jupyter/build/versionUpdating.kt
- kotlin-jupyter-plugin/src/main/kotlin/org/jetbrains/kotlinx/jupyter/plugin/options.kt
- settings.gradle.kts
> Update Changelog and fix Gradle plugin sources publication

- resources/notebook-extension/kernel.js
> Fix completion starting logic, avoid preventDefault

- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/libraries/JupyterIntegration.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/libraries/LibraryDefinition.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/libraries/LibraryDefinitionImpl.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/renderersHandling.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/throwableRendering.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/util/reflecton.kt
- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/codegen/ThrowableRenderersProcessor.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/codegen/ThrowableRenderersProcessorImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/protocol.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/evalResults.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/impl/CellExecutorImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/impl/SharedReplContext.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/CustomLibraryResolverTests.kt
This PR adds the ability to render exceptions via API. Renderers should return `DisplayResult`
Fix #332
> Add exceptions rendering

- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/util/acceptanceRules.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/libraries/LibrariesScanner.kt
Adds support for integrationTypeNameRules inside JUnit tests. Might need some extra work, but it's a start :)
> integrationTypeNameRules support for LibrariesScanner

- build.gradle.kts
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/Notebook.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/libraries/connection.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/renderersHandling.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/util/serializers.kt
- samples/Comms.ipynb
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/apiImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/config.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/connection.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/execution.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/ikotlin.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/CommManagerImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/JupyterConnectionInternal.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/message.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/message_types.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/protocol.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/creating/BaseReplFactory.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/creating/DefaultReplFactory.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/creating/MockJupyterConnection.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/creating/ReplFactory.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/creating/creatingUtil.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/KernelServerTest.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/KernelServerTestsBase.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/executeTests.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/testUtil.kt
Fixes #366
Should also partially fix the needs of #375
> Add socket messages callbacks and comms API

- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/libraries/gradleLike.kt
- jupyter-lib/lib/src/main/kotlin/jupyter/kotlin/ScriptTemplateWithDisplayHelpers.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/ReplTests.kt
> Add Gradle-like API for adding dependencies

- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/KotlinKernelHost.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/results.kt
- jupyter-lib/lib/src/main/kotlin/jupyter/kotlin/ScriptTemplateWithDisplayHelpers.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/apiImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/connection.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/JupyterConnectionInternal.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/protocol.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/impl/CellExecutorImpl.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/testUtil.kt
* Add nullable `id` argument to `ScriptTemplateWithDisplayHelpers.DISPLAY` and `KotlinKernelHost.display` methods in kernel API.
* Add `overrideId` argument to `DisplayResult.toJson` method
> Support display id in `display(value)` API.

- src/main/kotlin/org/jetbrains/kotlinx/jupyter/apiImpl.kt
Fix concurrent read/write in a list of displays.
> Fix race condition in `DisplayContainerImpl.displays` list.

- binder/apt.txt
- binder/start
The Kotlin kernel currently fails when this repo is launched on mybinder.org:
```
...
Listening for transport dt_socket at address: 1044
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at …
```
> mybinder: Update to Java 11

- docs/libraries.md
The link in the current docs resulted in a 404. I changed the link to the same file in the official repository.
> Fix link to dataframe integration example.

- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/message_types.kt
Moved cache in message_type serializer to ConcurrentHashMap to avoid concurrent modification exceptions. ConcurrentHashMap seems a good fit due to low overhead when reading from the map (which is the main purpose of a cache).
Updated both MessageTypeSerializer and DetailsLevelSerializer.
> Moved cache in message_type serializer to ConcurrentHashMap

- docs/README.md
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/fieldsHandlingEx.kt
- jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/renderersHandling.kt
- jupyter-lib/lib/src/main/kotlin/jupyter/kotlin/context.kt
- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/codegen/FieldsProcessorInternal.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/codegen/FieldsProcessorImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/ContextUpdater.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/impl/CellExecutorImpl.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/AbstractReplTest.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/CustomLibraryResolverTests.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/TypeConverterTests.kt
Result field doesn't have Kotlin property representation. To handle it, information about corresponding Java field was added to the low-level API. So, low-level API is broken, but seemingly no one uses it. High-level API was left semantically unchanged (it still doesn't process java fields without corresponding Kotlin properties). `ResultFieldUpdateHandler` class was added to handle this particular use case.
> Add API for handling result field with a type converter API

- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/debug/debugIntegrationUtility.kt
- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/creating/ReplComponentsProviderBase.kt
- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/notebook/impl/NotebookImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/ikotlin.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/messaging/MessageHandlerImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/repl/impl/ReplForJupyterImpl.kt
- src/main/kotlin/org/jetbrains/kotlinx/jupyter/util.kt
This way, newer version of kernel will keep thread for creating breakpoints
> Introduce class for setting up debug integration

- docs/libraries.md
Update the link to DataFrame tests (previous was 404). Add link to mentioned `JupyterReplTestingTest`.
> Fix links to JupyterIntegration example tests

- docs/libraries.md
Commit 0819a28ca858481fe0f2fc380250f40b4fe6af7d changed the location of `JupyterReplTestingTest.kt`. This PR adjusts sources to changes.
> Update `JupyterReplTestingTest` reference

- build.gradle.kts
- gradle/libs.versions.toml
- jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/libraries/LibraryResolver.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/EmbeddingTest.kt
- src/test/kotlin/org/jetbrains/kotlinx/jupyter/test/repl/AbstractReplTest.kt
This PR ensures we load the same dependencies for the `implementation` and `embeddedKernel` configurations. Tests have also been added for the cases that prompted this change.
> Streamline embedded dependencies
